# user_management/docker-compose.yml

version: '3'
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 000000x@X
      MYSQL_DATABASE: user_management
    networks:
      - bridge

  auth_service:
    image: auth_service
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    networks:
      - bridge

  user_service:
    image: user_service
    ports:
      - "5002:5002"
    depends_on:
      - mysql_db
    networks:
      - bridge

  ui_service:
    image: ui_service
    ports:
      - "5003:5003"
    depends_on:
      - auth_service
      - user_service
    networks:
      - bridge

networks:
  bridge:
