apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service
          image: ui_service
          ports:
            - containerPort: 5003
